using System;
using Indiefreaks.Xna.Core;
using Indiefreaks.Xna.Sessions;

namespace Indiefreaks.Xna.Logic
{
    /// <summary>
    /// The Command class encapsulates methods that will be executed by the current session when necessary
    /// A Command instance contains a clientExecution delegate that is executed on the player machine when set to Local and LocalAndServer. The serverExecution gets called on the
    /// session host when set to Server. Finally, the ApplyServerResult is called back on all players when the ServerExecution delegate returns.
    /// Each Command is identified by its Id that is automatically generated by the Session so that Remote Command calls are always consistent.
    /// </summary>
    public sealed class Command : IDisposable
    {
        public delegate object ClientCommand(Command command);

        public delegate object ServerCommand(Command command, object networkValue);

        public delegate void ApplyServerCommand(Command command, object networkValue);
        
        private static ushort _count;

        /// <summary>
        /// Creates a new Command instance
        /// </summary>
        /// <param name="condition"></param>
        /// <param name="clientExecution">The method that will be executed</param>
        /// <param name="serverExecution"></param>
        /// <param name="applyServerResult"></param>
        /// <param name="comandType">The CommandType of this Command</param>
        /// <param name="networkValueType">The type of the value that is returned by the Execution delegate, if the command doesn't returns a value, you can set this to null to limit network data transfer</param>
        /// <param name="dataTransferOptions">Defines options for network packet transmission</param>
        /// <param name="frequency">Defines the frequency at which the current command will be processed</param>
        public Command(Condition condition, ClientCommand clientExecution, ServerCommand serverExecution,
                         ApplyServerCommand applyServerResult, CommandType comandType, Type networkValueType,
                         DataTransferOptions dataTransferOptions, ExecutionFrequency frequency)
        {
            if (networkValueType != null && !networkValueType.IsValueType && networkValueType != typeof(string) && networkValueType != typeof(byte[]))
                throw new CoreException("DataType must be a ValueType.");

            LocalId = _count++;
            Condition = condition;
            ClientExecution = clientExecution;
            ServerExecution = serverExecution;
            ApplyServerResult = applyServerResult;
            Type = comandType;
            NetworkValueType = networkValueType;
            TransferOptions = dataTransferOptions;
            Frequency = frequency;
        }

        #region Create Local Command

        public static Command CreateLocalCommand(Condition condition, ClientCommand clientCommand, ExecutionFrequency frequency)
        {
            return new Command(condition, clientCommand, null, null, CommandType.Local, null, DataTransferOptions.None, frequency);
        }

        public static Command CreateLocalCommand(Condition condition, ClientCommand clientCommand)
        {
            return new Command(condition, clientCommand, null, null, CommandType.Local, null, DataTransferOptions.None, ExecutionFrequency.FullUpdate60Hz);
        }

        public static Command CreateLocalCommand(ClientCommand clientCommand, ExecutionFrequency frequency)
        {
            return CreateLocalCommand(null, clientCommand, frequency);
        }

        public static Command CreateLocalCommand(ClientCommand clientCommand)
        {
            return CreateLocalCommand(null, clientCommand, ExecutionFrequency.FullUpdate60Hz);
        }
        
        #endregion

        #region Create Server Only Command 

        public static Command CreateServerCommand(Condition condition, ServerCommand serverCommand, ExecutionFrequency frequency)
        {
            return new Command(condition, null, serverCommand, null, CommandType.Server, null, DataTransferOptions.None, frequency);
        }

        public static Command CreateServerCommand(Condition condition, ServerCommand serverCommand)
        {
            return new Command(condition, null, serverCommand, null, CommandType.Server, null, DataTransferOptions.None, ExecutionFrequency.FullUpdate60Hz);
        }

        public static Command CreateServerCommand(ServerCommand serverCommand, ExecutionFrequency frequency)
        {
            return CreateServerCommand(null, serverCommand, frequency);
        }

        public static Command CreateServerCommand(ServerCommand serverCommand)
        {
            return CreateServerCommand(null, serverCommand, ExecutionFrequency.FullUpdate60Hz);
        }

        #endregion

        #region Create Server & Apply on client Command

        public static Command CreateServerCommand(Condition condition, ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions, ExecutionFrequency frequency)
        {
            return new Command(condition, null, serverCommand, applyServerResult, CommandType.Server, typeOfDataExchanged, dataTransferOptions, frequency);
        }

        public static Command CreateServerCommand(Condition condition, ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions)
        {
            return new Command(condition, null, serverCommand, applyServerResult, CommandType.Server, typeOfDataExchanged, dataTransferOptions, ExecutionFrequency.FullUpdate60Hz);
        }

        public static Command CreateServerCommand(ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions, ExecutionFrequency frequency)
        {
            return CreateServerCommand(null, serverCommand, applyServerResult, typeOfDataExchanged, dataTransferOptions, frequency);
        }

        public static Command CreateServerCommand(ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions)
        {
            return CreateServerCommand(null, serverCommand, applyServerResult, typeOfDataExchanged, dataTransferOptions, ExecutionFrequency.FullUpdate60Hz);
        }

        #endregion

        #region Create Local & Server Command

        public static Command CreateLocalAndServerCommand(Condition condition, ClientCommand clientCommand, ServerCommand serverCommand, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions, ExecutionFrequency frequency)
        {
            return new Command(condition, clientCommand, serverCommand, null, CommandType.LocalAndServer, typeOfDataExchanged, dataTransferOptions, frequency);
        }

        public static Command CreateLocalAndServerCommand(Condition condition, ClientCommand clientCommand, ServerCommand serverCommand, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions)
        {
            return new Command(condition, clientCommand, serverCommand, null, CommandType.LocalAndServer, typeOfDataExchanged, dataTransferOptions, ExecutionFrequency.FullUpdate60Hz);
        }
        
        public static Command CreateLocalAndServerCommand(ClientCommand clientCommand, ServerCommand serverCommand, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions, ExecutionFrequency frequency)
        {
            return CreateLocalAndServerCommand(clientCommand, serverCommand, typeOfDataExchanged, dataTransferOptions, frequency);
        }

        public static Command CreateLocalAndServerCommand(ClientCommand clientCommand, ServerCommand serverCommand, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions)
        {
            return CreateLocalAndServerCommand(clientCommand, serverCommand, typeOfDataExchanged, dataTransferOptions);
        }

        #endregion

        #region Create Local & Server & Apply on client Command

        public static Command CreateLocalAndServerCommand(Condition condition, ClientCommand clientCommand, ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions, ExecutionFrequency frequency)
        {
            return new Command(condition, clientCommand, serverCommand, applyServerResult, CommandType.LocalAndServer, typeOfDataExchanged, dataTransferOptions, frequency);
        }

        public static Command CreateLocalAndServerCommand(Condition condition, ClientCommand clientCommand, ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions)
        {
            return new Command(condition, clientCommand, serverCommand, applyServerResult, CommandType.LocalAndServer, typeOfDataExchanged, dataTransferOptions, ExecutionFrequency.FullUpdate60Hz);
        }

        public static Command CreateLocalAndServerCommand(ClientCommand clientCommand, ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions, ExecutionFrequency frequency)
        {
            return CreateLocalAndServerCommand(null, clientCommand, serverCommand, applyServerResult, typeOfDataExchanged, dataTransferOptions, frequency);
        }

        public static Command CreateLocalAndServerCommand(ClientCommand clientCommand, ServerCommand serverCommand, ApplyServerCommand applyServerResult, Type typeOfDataExchanged, DataTransferOptions dataTransferOptions)
        {
            return CreateLocalAndServerCommand(null, clientCommand, serverCommand, applyServerResult, typeOfDataExchanged, dataTransferOptions, ExecutionFrequency.FullUpdate60Hz);
        }

        #endregion

        ~Command()
        {
            Dispose(false);
        }

        /// <summary>
        /// This property is controlled by the Session when a command gets executed on the server so that it isn't called twice until it returns.
        /// </summary>
        public bool WaitingForServerReply { get; set; }

        /// <summary>
        /// Returns the local Command Id
        /// </summary>
        /// <remarks>Differs from the Id property because the Command is created locally when added to a Behavior but to make sure server and clients share
        /// the same unique Id, we use this to define their order of creation and later apply the right Id value when the server registers its own.
        /// </remarks>
        public ushort LocalId { get; private set; }

        /// <summary>
        /// Returns the Id of the Command
        /// </summary>
        public ushort Id { get; set; }

        /// <summary>
        /// Defines options for network packet transmission
        /// </summary>
        public DataTransferOptions TransferOptions { get; private set; }

        /// <summary>
        /// The method that will be executed to define if the current command should execute.
        /// </summary>
        public Condition Condition { get; private set; }

        /// <summary>
        /// The method that will be executed on the client
        /// </summary>
        /// <remarks>
        /// The returned value by this delegate will be used by the Session host to call the ServerExecution delegate in the server
        /// It is used to synchronize values accross the Network.
        /// Make sure to match the returned type with the NetworkValueType set on the command constructor
        /// </remarks>
        public ClientCommand ClientExecution { get; private set; }

        /// <summary>
        /// The method that will be executed on the server side if CommandType is set to LocalAndServer or Server.
        /// </summary>
        /// <remarks>If the Command is of type LocalAndServer and Server, the value returned by the ClientExecution method will be passed to this method and can be used
        /// to compute the value that will be then applied on all clients</remarks>
        public ServerCommand ServerExecution { get; private set; }

        /// <summary>
        /// The method that will be executed on clients when the server ended executing a LocalAndServer or Server CommandType
        /// </summary>
        public ApplyServerCommand ApplyServerResult { get; private set; }

        /// <summary>
        /// Returns the CommandType of this Command
        /// </summary>
        public CommandType Type { get; private set; }

        /// <summary>
        /// Returns the Type used by the value returned by Execution
        /// </summary>
        public Type NetworkValueType { get; private set; }

        /// <summary>
        /// Gets or sets the value that will be shared across the network
        /// </summary>
        public object NetworkValue { get; set; }

        /// <summary>
        /// Gets or sets the frequency at which the current command will be considered for execution
        /// </summary>
        public ExecutionFrequency Frequency
        {
            get { return _executionFrequency; } 
            set
            {
                if (_executionFrequency != value)
                {
                    _executionFrequency = value;
                    switch (_executionFrequency)
                    {
                        case ExecutionFrequency.PartialUpdate1Hz:
                            _frequencyValue = 1f;
                            break;
                        case ExecutionFrequency.PartialUpdate5Hz:
                            _frequencyValue = 5f;
                            break;
                        case ExecutionFrequency.PartialUpdate10Hz:
                            _frequencyValue = 10f;
                            break;
                        case ExecutionFrequency.PartialUpdate15Hz:
                            _frequencyValue = 15f;
                            break;
                        case ExecutionFrequency.HalfUpdate30Hz:
                            _frequencyValue = 30f;
                            break;
                        default:
                        case ExecutionFrequency.FullUpdate60Hz:
                            _frequencyValue = 60f;
                            break;
                    }
                }
            }
        }
        private ExecutionFrequency _executionFrequency;
        private float _frequencyValue;

        /// <summary>
        /// Gets this Command Behavior to access its Agent or even the Agent ParentObject.
        /// </summary>
        public Behavior Behavior { get; internal set; }

        #region Implementation of IDisposable

        /// <summary>
        /// Exécute les tâches définies par l'application associées à la libération ou à la redéfinition des ressources non managées.
        /// </summary>
        /// <filterpriority>2</filterpriority>
        public void Dispose()
        {
            Dispose(true);
        }

        #endregion

        private void Dispose(bool disposing)
        {
            if (disposing)
            {
                Condition = null;
                ClientExecution = null;
                ServerExecution = null;
                ApplyServerResult = null;
            }
        }

        private float _tick;

        internal void Process(float elapsed)
        {
            if(_tick < 1f / _frequencyValue)
                return;

            _tick = 0f;

            if (Condition != null)
            {
                if (!Condition.Invoke())
                    return;
            }

            if (WaitingForServerReply)
                return;

            // If command is local, we just execute the command
            if (Type == CommandType.Local)
            {
                ClientExecution(this);
            }
            // If command is local & server, we execute the command locally and request the command to be executed on the server. Once
            // executed, the server will get back to us requesting to perform the command with a server computed value.
            else if (Type == CommandType.LocalAndServer)
            {
                NetworkValue = ClientExecution(this);

                SessionManager.CurrentSession.ExecuteCommandOnServer(this);
            }
            // If command is server only, we ask the server to execute it
            else
            {
                if (SessionManager.CurrentSession.IsHost)
                {
                    NetworkValue = ServerExecution(this, null);

                    if (ApplyServerResult != null)
                        SessionManager.CurrentSession.ExecuteServerCommandOnClients(this);
                }
            }
        }

        internal void UpdateTick(float elapsed)
        {
            _tick += elapsed;
        }
    }

    /// <summary>
    /// The CommandType enumeration tells a Command where it is executed
    /// </summary>
    public enum CommandType
    {
        Local,
        LocalAndServer,
        Server,
    }
}